-- Find the total number of couriers handled by each employee. 
SELECT e.EmployeeID, e.Name, COUNT(c.CourierID) AS TotalCouriersHandled
FROM Employees e
JOIN Couriers c ON e.EmployeeID = c.EmployeeID
GROUP BY e.EmployeeID, e.Name
ORDER BY TotalCouriersHandled DESC;

-- Calculate the total revenue generated by each location.
SELECT l.LocationID, l.LocationName, SUM(p.Amount) AS TotalRevenue
FROM Payments p
JOIN Locations l ON p.LocationID = l.LocationID
GROUP BY l.LocationID, l.LocationName
ORDER BY LocationID ;

-- Find the total number of couriers delivered to each location. 
select l.locationID, l.locationName,count(c.courierID) as total_num_courier
from couriers c
join locations l on c.locationID = l.locationID
group by l.locationID, l.locationName
order by locationID;

-- Find the courier with the highest average delivery time: 
select courierID , senderName, receiverName, avg(datediff(deliveryDate,shipmentDate)) as AvgDeliveryTime from couriers
group by courierID
order by AvgDeliveryTime desc limit 1;

-- Find Locations with Total Payments Less Than a Certain Amount
select l.locationName,l.locationID, sum(p.amount) as total_payment from payments p
join locations l on p.locationID = l.locationID
group by l.locationName, l.locationID
having total_payment<500
order by total_payment desc;
 
-- Calculate Total Payments per Location 
select l.locationID, l.locationName, sum(p.amount) as totalPayment from locations l
join payments p on l.locationID = p.locationID
group by l.locationID,l.locationName
order by totalPayment;

/*Retrieve couriers who have received payments totaling more than $1000 in a specific location 
(LocationID = X): */
select c.courierID, c.senderName, c.receiverName, p.paymentID, sum(p.amount) as total_payment,l.locationID from couriers c
join payments p on c.courierID = p.courierID
join locations l on c.locationID = l.locationID
where l.locationID = 3
group by p.paymentID, c.courierID, c.senderName, c.receiverName
HAVING Total_Payment > 1000;

/*Retrieve couriers who have received payments totaling more than $1000 after a certain date 
(PaymentDate > 'YYYY-MM-DD'): */
select c.courierID,c.senderName,c.receiverName,p.paymentID,p.paymentDate, sum(p.amount) as paymentTot from couriers c 
join payments p on c.courierID = p.courierID
where p.paymentDate > curdate()
group by c.courierID,c.senderName,c.receiverName,p.paymentID
having paymentTot > 1000;

/* Retrieve locations where the total amount received is more than $5000 before a certain date 
(PaymentDate > 'YYYY-MM-DD') */
select l.locationID, l.locationName, p.paymentID, p.paymentDate ,sum(p.amount) as total_amount from locations l
join payments p on l.locationID = p.locationID
where p.paymentDate > curdate()
group by l.locationID, l.locationName, p.paymentID, p.paymentDate
having total_amount > 5000;
